//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectShedule.Language.Resources.Pages.Setting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectShedule.Language.Resources.Pages.Setting.SettingResources", typeof(SettingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar:.
        /// </summary>
        public static string CarouselHeaderLabel {
            get {
                return ResourceManager.GetString("CarouselHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner radius:.
        /// </summary>
        public static string CornerRadiusDopTextLabel {
            get {
                return ResourceManager.GetString("CornerRadiusDopTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode:.
        /// </summary>
        public static string DarkModeDopTextLabel {
            get {
                return ResourceManager.GetString("DarkModeDopTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shedule Delete Notes:.
        /// </summary>
        public static string DeleteNotesHeaderLabel {
            get {
                return ResourceManager.GetString("DeleteNotesHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal request:.
        /// </summary>
        public static string DeleteQuestionDopTextLabel {
            get {
                return ResourceManager.GetString("DeleteQuestionDopTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string EndLabel {
            get {
                return ResourceManager.GetString("EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Mark:.
        /// </summary>
        public static string EventsHeaderLabel {
            get {
                return ResourceManager.GetString("EventsHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffLabel {
            get {
                return ResourceManager.GetString("OffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnLabel {
            get {
                return ResourceManager.GetString("OnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity:.
        /// </summary>
        public static string OpacityDopTextLabel {
            get {
                return ResourceManager.GetString("OpacityDopTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string SizeDopTextLabel {
            get {
                return ResourceManager.GetString("SizeDopTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string ThemeHeaderLabel {
            get {
                return ResourceManager.GetString("ThemeHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years Range:.
        /// </summary>
        public static string YearsRangeLabel {
            get {
                return ResourceManager.GetString("YearsRangeLabel", resourceCulture);
            }
        }
    }
}
